### PR TITLE
Feature | Accordion

### PR DESCRIPTION
**Pull request by EstebanBorai**
* Use `yarn dev` to run development server
* Extend the recursion limit to 1024
* Implement the Accordion component

### CODE REVIEW

**Review by Armiixteryx — APPROVED** [review]
Looks good.

**Review by angel-afonso — APPROVED** [review]
Excellent :rocket:

**Review by EstebanBorai — COMMENTED** [review]
Checked!

**Review by Davejs136 — APPROVED** [review]
Nice!

**Pull request merged**
